### ISSUE TITLE
Backspace messes with kerning of smaller letters

### ISSUE THREAD

**Issue by LAK132** [LAK132/MegaWAT#2]
Typing in a string with tall and short characters (`Hello World`) in a multiline font works fine, however if you delete some of the small characters (`Hll Wld`) then retype them, the blank space above (or below) the small characters causes kerning issues with the taller (or under hanging) characters

Currently avoiding by re-rendering the entire line each time backspace is pressed.

**Comment by gardners** [comment]
Please provide an example of how to reproduce the problem.

**Comment by LAK132** [comment]
Fixed in 4ac9f9645001bd0841ece95aa904ce318a5819ec
